# ref https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - uses: actions/checkout@main

    - run: corepack enable

    - uses: actions/setup-node@main
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - run: pnpm publish --tag latest --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
